"""Step 5 — lens analysts: prompts, validation, retries, id mapping, detail round (FakeLLM only)."""
from __future__ import annotations

import asyncio
import copy

import pytest

from analytics.agents import AgentRunner
from analytics.context import ContextBuilder, ContextConfig
from analytics.lenses import (
    LENS_DEFS, ScienceAnswer, fake_lens_llm, lens_spec, lens_user_prompt, make_validator, run_lens, run_lenses,
)
from analytics.lenses.fake import _science
from analytics.llm import FakeLLM, LLMRequest, LLMSettings, make_llm
from analytics.schemas import LENSES
from evidence_bundle import FIXTURES_DIR, load_bundle


@pytest.fixture(scope="module")
def bundle():
    return load_bundle(FIXTURES_DIR / "il17_crohn_now.json")


@pytest.fixture(scope="module")
def ctx(bundle):
    return ContextBuilder().build(bundle)


def runner(fake: FakeLLM) -> AgentRunner:
    return AgentRunner(make_llm(LLMSettings(provider="fake"), fake=fake))


def science_answer(ctx) -> dict:
    """A valid science answer generated by the offline stand-in for this context."""
    prompt = lens_user_prompt("science", ctx)
    from analytics.llm import Message
    return _science(LLMRequest(messages=[Message(role="system", content=""), Message(role="user", content=prompt)]))


def strip_kill_citations(ans: dict, bundle, ctx) -> dict:
    """Same answer, but every claim cites only a neutral (non-conflict) evidence id."""
    from analytics.lenses.validation import kill_short_ids
    kills = set(kill_short_ids(bundle, ctx, "science"))
    neutral = next(i for i in ctx.lenses["science"].full_ids if i not in ctx.lenses["science"].conflict_ids)
    out = copy.deepcopy(ans)
    for c in out["claims"]:
        c["evidence"] = [{"id": neutral, "stance": "supports"}]
    assert kills
    return out


def test_prompts_render_for_every_lens(ctx):
    for lens in LENSES:
        system = lens_spec(lens).full_system_prompt()
        user = lens_user_prompt(lens, ctx)
        assert "Use only the evidence provided" in system and "Scoring rubric" in system
        assert "Answer format" in system and "$" not in user.split("## Your task")[1][:200]
        for q in LENS_DEFS[lens].questions:
            assert q in user


def test_validator_accepts_valid_and_rejects_bad_citations(bundle, ctx):
    validate = make_validator(bundle, ctx, "science")
    good = ScienceAnswer.model_validate(science_answer(ctx))
    assert validate(good) == []

    bad = strip_kill_citations(science_answer(ctx), bundle, ctx)
    bad["claims"][0]["evidence"] = [{"id": "E999", "stance": "supports"}]
    errors = validate(ScienceAnswer.model_validate(bad))
    assert any("unknown id" in e for e in errors)
    assert any("KILL SIGNAL" in e for e in errors)  # kill conflicts are no longer cited


def test_validator_rejects_ids_not_shown_to_the_lens(bundle):
    tight = ContextBuilder(ContextConfig(budget_tokens=1200)).build(bundle)
    dropped = tight.lenses["science"].dropped_ids[0]
    ans = science_answer(tight)
    ans["claims"][-1]["evidence"].append({"id": dropped, "stance": "supports"})
    errors = make_validator(bundle, tight, "science")(ScienceAnswer.model_validate(ans))
    assert any("not in your context" in e and dropped in e for e in errors)


def test_retry_fixes_missing_kill_citation(bundle, ctx):
    good = science_answer(ctx)
    bad = strip_kill_citations(good, bundle, ctx)
    fake = FakeLLM(script={"lens:science": [bad, good]})
    run = asyncio.run(run_lens("science", bundle, ctx, runner(fake)))
    assert run.result.status == "ok" and len(run.traces) == 2
    assert "KILL SIGNAL" in fake.calls[1].messages[-1].content


def test_aggregate_citation_expands_to_capped_members(bundle, ctx):
    agg_id, members = next(iter(ctx.id_map["aggregates"].items()))
    ans = science_answer(ctx)
    lc = ctx.lenses["science"]
    if agg_id not in lc.aggregate_ids:  # aggregate lives in the market lens; test the mapping there
        from analytics.lenses.fake import _market
        from analytics.llm import Message
        prompt = lens_user_prompt("market", ctx)
        ans = _market(LLMRequest(messages=[Message(role="system", content=""), Message(role="user", content=prompt)]))
        ans["claims"][-1]["evidence"] = [{"id": agg_id, "stance": "supports"}]
        run = asyncio.run(run_lens("market", bundle, ctx, runner(FakeLLM(script={"lens:market": ans}))))
    else:
        ans["claims"][-1]["evidence"] = [{"id": agg_id, "stance": "supports"}]
        run = asyncio.run(run_lens("science", bundle, ctx, runner(FakeLLM(script={"lens:science": ans}))))
    from analytics.lenses.mapping import MAX_AGGREGATE_MEMBERS
    cited = {r.evidence_id for c in run.result.claims for r in c.evidence}
    assert set(members[:MAX_AGGREGATE_MEMBERS]) <= cited
    assert not set(members[MAX_AGGREGATE_MEMBERS:]) & cited


def test_lens_without_evidence_is_skipped_without_llm(bundle, ctx):
    from analytics.findings.unknowns import merge_unknowns
    empty = ctx.model_copy(deep=True)
    lc = empty.lenses["science"]
    lc.full_ids, lc.brief_ids, lc.aggregate_ids, lc.dropped_ids = [], [], [], []
    llm = FakeLLM(script={})
    run = asyncio.run(run_lens("science", bundle, empty, runner(llm)))
    assert run.result.status == "skipped" and run.traces == []
    assert run.result.unknowns
    assert any("no public evidence" in u.question for u in merge_unknowns(bundle, {"science": run.result}))


def test_detail_round_sends_requested_cards(bundle):
    tight = ContextBuilder(ContextConfig(budget_tokens=1200)).build(bundle)
    dropped = tight.lenses["science"].dropped_ids[0]
    first = science_answer(tight)
    first["need_detail"] = [dropped]
    second = copy.deepcopy(first)
    second["need_detail"] = []
    second["claims"][-1]["evidence"].append({"id": dropped, "stance": "supports"})  # now allowed
    fake = FakeLLM(script={"lens:science": [first, second]})
    run = asyncio.run(run_lens("science", bundle, tight, runner(fake)))
    assert run.detail_ids == [dropped] and run.result.status == "ok"
    assert "ADDITIONAL DETAIL" in fake.calls[1].messages[1].content and f"[{dropped}]" in fake.calls[1].messages[1].content
    full = tight.resolve(dropped)[0]
    assert full in {r.evidence_id for c in run.result.claims for r in c.evidence}


def test_lens_fails_cleanly_after_max_attempts(bundle, ctx):
    run = asyncio.run(run_lens("science", bundle, ctx, runner(FakeLLM(script={"lens:science": "not json"}))))
    assert run.result.status == "failed" and run.result.errors and len(run.traces) == 3


def test_end_to_end_fake_lenses_flip_with_cutoff():
    now = load_bundle(FIXTURES_DIR / "il17_crohn_now.json")
    then = load_bundle(FIXTURES_DIR / "il17_crohn_2011.json")
    r_now = asyncio.run(run_lenses(now, ContextBuilder().build(now), runner(fake_lens_llm())))
    r_then = asyncio.run(run_lenses(then, ContextBuilder().build(then), runner(fake_lens_llm())))
    assert all(r.result.status == "ok" for r in [*r_now.values(), *r_then.values()])
    assert r_now["science"].result.score == 0 and r_then["science"].result.score == 3
    ids = set(now.by_id())
    for r in r_now.values():
        for c in r.result.claims:
            assert {e.evidence_id for e in c.evidence} <= ids  # every claim traceable to real evidence
    chain = r_now["science"].result.params["translation_chain"]
    assert [link["step"] for link in chain][-1] == "patient_benefit"
